# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = embedded_soft_dev
SUB_SRC_FILES = \
    preface.xml \
    ch01_emb_dev_background.xml \
    ch02_emb_dev_basic_logic.xml \
    ch03_emb_dev_basic_concept.xml \
    ch04_emb_dev_composition.xml \
    ch05_emb_dev_crosstoolchain.xml \
    ch06_emb_dev_burn.xml \
    ch07_emb_dev_tools.xml \
    ch08_emb_dev_design.xml \
    ch09_emb_dev_cpu.xml \
    ch10_emb_dev_peripheral.xml \
    ch11_emb_dev_related_hardware.xml \
    ch12_emb_dev_vendor.xml \
    ch13_emb_dev_inter_bus_protocol.xml \
    ch14_emb_dev_faq.xml \
    ch15_emb_dev_article.xml \
    ch16_emb_dev_res.xml \
    ch17_emb_dev_how_learn.xml \
    reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk